version: '3.5'

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: admin
          POSTGRES_USER: admin
    ports:
      - "5400:5432"

